using Photon.Pun;
using UnityEngine;
using System.Collections;
using System;
using UnityEngine.SceneManagement;
using System.Collections.Generic; // ФкЗчЦО ЛчПыРЛ РЇЧи ЧЪПф

public class CustomAvatarController : MonoBehaviourPunCallbacks
{
    public bool canMove = true;           // РЬЕП АЁДЩ ПЉКЮ (АјАн СпПЁДТ false)
    public float moveSpeed = 5f;          // АШБт МгЕЕ
    public float sprintSpeed = 8f;        // ДоИЎБт МгЕЕ
    public float rotationSpeed = 10f;
    public float cameraDistance = 4f;
    public float cameraHeight = 2f;
    public float attackDuration = 1.8f;     // АјАн ОжДЯИоРЬМЧ СіМг НУАЃ (УЪ)
    [SerializeField] private GameObject weapon;
    [SerializeField] private Canvas gameover;
    [SerializeField] private Canvas win;
    [SerializeField] private Camera _mainCamera;
    [SerializeField] private GameObject myMesh;
    [SerializeField] private BoxCollider myCollider;

    private Animator _animator;
    private bool _isRunning;
    private bool _isAttacking;
    private bool _isWin = false;
    private float _currentYRotation = 0f;
    private bool _isDead = false;
    private int _playerConut;
    private RaycastHit hit;

    public Vector3 boxSize = new Vector3(0.5f, 0.5f, 0.5f);   // ЙкНКРЧ ХЉБт
    public Vector3 castDirection = Vector3.forward;   // ФГНКЦЎ ЙцЧт
    public float castDistance = 3f;

    // ЛѓХТИІ ТќСЖЧв enum Л§МК
    public enum AvatarState
    {
        Idle,
        Move,
        Attack
    }
    private AvatarState currentState = AvatarState.Idle; // БтКЛ ЛѓХТДТ Idle

    private void Awake()
    {
        _animator = GetComponent<Animator>();

        if (photonView.IsMine)
        {
            if (_mainCamera != null)
            {
                GameObject cameraObject = new GameObject("PlayerCamera");
                _mainCamera = cameraObject.AddComponent<Camera>();
                _mainCamera.tag = "MainCamera"; // ФЋИоЖѓРЧ ХТБзИІ "MainCamera"ЗЮ МГСЄ
            }
            if (_animator == null)
            {
                Debug.LogError("AnimatorАЁ ОјНРДЯДй! ЧСИЎЦеПЁ AnimatorИІ УпАЁЧЯММПф.", gameObject);
            }
        }
        else
        {
            _mainCamera = GetComponentInChildren<Camera>();
            if (_mainCamera != null)
            {
                _mainCamera.gameObject.SetActive(false); // ДйИЅ ЧУЗЙРЬОюРЧ ФЋИоЖѓДТ КёШАМКШ­
                _animator = null;
            }
        }
    }

    private void Start()
    {
        _isDead = false;
        _isWin = false;
        if (photonView.IsMine)
        {
            _animator.SetBool("isDie", false);
        }
    }
    private void Update()
    {
        HandlePlayerController();
        if (SceneManager.GetActiveScene().name != "Map") return;

        // ЗЮФУ ЧУЗЙРЬОюРЬАэ ОЦСї СзСі ОЪОвДйИщ НТИЎ СЖАЧ УМХЉ
        if (photonView.IsMine && !_isDead)
        {
            // PhotonNetwork.CurrentRoom.PlayerCountАЁ 1РЬИщ ИЖСіИЗ ЧУЗЙРЬОюРг
            if (SpawnManager.Instance._playerCount <= 1)
            {
                _isWin = true;
                Win();
            }
        }
    }

    private void OnDrawGizmos()
    {
        Quaternion characterRotation = transform.rotation;
        Gizmos.color = Color.red;
        Gizmos.DrawWireCube(transform.position + characterRotation * castDirection * castDistance / 2, boxSize);

        RaycastHit hit;
        if (Physics.BoxCast(transform.position, boxSize / 2, characterRotation * castDirection, out hit, characterRotation, castDistance))
        {
            Gizmos.color = Color.green;
            Gizmos.DrawSphere(hit.point, 0.2f);
        }
    }

    // ЧУЗЙРЬОю СІОю (ОжДЯИоРЬМЧ Йз БтДЩ)
    private void HandlePlayerController()
    {
        if (!photonView.IsMine || _isDead) return;

        FreeCamControl();

        _isRunning = Input.GetKey(KeyCode.LeftShift);
        _animator.SetBool("isRunning", _isRunning);

        if (Input.GetMouseButtonDown(0) && !_isAttacking)
        {
            HandleAttack();
            return;
        }

        if (!_isAttacking && canMove)
        {
            HandleMovement();
        }
    }

    // ЧУЗЙРЬОю СІОю (РЬЕП)
    private void HandleMovement()
    {
        float horizontal = Input.GetAxis("Horizontal");
        float vertical = Input.GetAxis("Vertical");
        Vector3 inputDirection = new Vector3(horizontal, 0f, vertical).normalized;

        if (inputDirection.magnitude >= 0.1f)
        {
            Vector3 cameraForward = _mainCamera.transform.forward;
            Vector3 cameraRight = _mainCamera.transform.right;
            cameraForward.y = 0f;
            cameraRight.y = 0f;
            cameraForward.Normalize();
            cameraRight.Normalize();
            Vector3 moveDirection = cameraForward * inputDirection.z + cameraRight * inputDirection.x;

            Quaternion targetRotation = Quaternion.LookRotation(moveDirection);
            transform.rotation = Quaternion.Lerp(transform.rotation, targetRotation, rotationSpeed * Time.deltaTime);

            float speed = _isRunning ? sprintSpeed : moveSpeed;

            SetState(AvatarState.Move);
            transform.Translate(moveDirection * speed * Time.deltaTime, Space.World);
        }
        else
        {
            SetState(AvatarState.Idle);
        }
    }

    // ЧУЗЙРЬОюРЧ ФЋИоЖѓ СІОю
    private void FreeCamControl()
    {
        float mouseX = Input.GetAxis("Mouse X");
        _currentYRotation += mouseX * rotationSpeed;
        Quaternion camRotation = Quaternion.Euler(0f, _currentYRotation, 0f);
        _mainCamera.transform.position = transform.position - camRotation * Vector3.forward * cameraDistance + Vector3.up * cameraHeight;
        _mainCamera.transform.LookAt(transform.position + Vector3.up * 1.5f);
    }

    // ЧУЗЙРЬОю АјАн ИоМ­Ех
    private void HandleAttack()
    {
        _isAttacking = true;
        canMove = false;
        SetState(AvatarState.Attack);
        _animator.SetTrigger("Attack");

        StartCoroutine(WaitForAttackAnimationToEnd());
    }

    // ЧУЗЙРЬОю АјАн ФкЗчЦО ММЦУ
    private IEnumerator WaitForAttackAnimationToEnd()
    {
        yield return new WaitForSeconds(attackDuration);

        _isAttacking = false;
        canMove = true;

        float horizontal = Input.GetAxis("Horizontal");
        float vertical = Input.GetAxis("Vertical");
        Vector3 inputDirection = new Vector3(horizontal, 0f, vertical);
        if (inputDirection.sqrMagnitude > 0.01f)
        {
            SetState(AvatarState.Move);
        }
        else
        {
            SetState(AvatarState.Idle);
        }
    }

    // enum(ЛѓХТ)ПЁ ИТУч ОжДЯИоРЬМЧ ValueММЦУ
    private void SetState(AvatarState newState)
    {
        if (_animator == null) return;

        if (currentState == newState) return;
        currentState = newState;

        switch (currentState)
        {
            case AvatarState.Idle:
                _animator.SetBool("isWalking", false);
                _animator.SetBool("isRunning", false);
                break;
            case AvatarState.Move:
                _animator.SetBool("isWalking", true);
                break;
            case AvatarState.Attack:
                _animator.SetBool("isWalking", false);
                _animator.SetBool("isRunning", false);
                break;
        }
    }

    // НТИЎ ИоМ­Ех
    private void Win()
    {
        // _isWinАЁ trueРЬАэ, ОЦСї СзСі ОЪОвДйИщ
        if (_isWin && !_isDead && photonView.IsMine)
        {
            win.gameObject.SetActive(true);
            UnlockCursor();
            GameManager.Instance.isWin = true;
        }
    }

    // ЛчИС ИоМ­Ех
    public void Die()
    {
        if (myMesh == null) return;

        if (photonView.IsMine)
        {
            StartCoroutine(DieAnim());
            GameManager.Instance.isDie = true;
        }
    }


    // ЛчИС ОжДЯИоРЬМЧ ФкЗчЦО
    private IEnumerator DieAnim()
    {
        _isDead = true;
        _animator.SetBool("isDie", true);
        _animator.SetTrigger("Die");

        yield return new WaitForSeconds(3.5f);

        // И№Еч ХЌЖѓРЬО№ЦЎПЁМ­ ИоНЌПЭ ФнЖѓРЬДѕИІ КёШАМКШ­ЧЯЕЕЗЯ RPC ШЃУт
        photonView.RPC("DisableMesh", RpcTarget.All);

        photonView.RPC("DecreasePlayerCountRPC", RpcTarget.All);

        // АдРг ПРЙі UIДТ ЗЮФУПЁМ­ИИ ЧЅНУ (ПјЧЯДТ АцПь И№Еч ХЌЖѓРЬО№ЦЎПЁМ­ ШАМКШ­ЧЯЗСИщ RPC ЛчПы)
        if (photonView.IsMine)
        {
            gameover.gameObject.SetActive(true);
            UnlockCursor();
        }
    }
    // ИЖПьНК РсБнИоМ­Ех
    public void UnlockCursor()
    {
        Cursor.lockState = CursorLockMode.None;
        Cursor.visible = true;
    }


    // ЧУЗЙРЬОю Мі УМХЉ ИоМ­Ех(Photon)
    [PunRPC]
    private void DecreasePlayerCountRPC()
    {
        SpawnManager.Instance._playerCount--;
    }

    // ЛчИСНУ Mesh ОШКИРЬАдЧЯДТ ИоМ­Ех (Photon)
    [PunRPC]
    private void DisableMesh()
    {
        // И№Еч ХЌЖѓРЬО№ЦЎПЁМ­ НЧЧрЕЧЕЕЗЯ ifЙЎ СІАХ
        myMesh.SetActive(false);
        myCollider.enabled = false;
    }

    // pvViewIdПЁ АЊРЬ РЯФЁЧЯДТ РЮНКХЯНКРЧ Die НЧЧр
    [PunRPC]
    private void LocalDie(int viewId)
    {
        Dictionary<int, AvatarSetNumber> dictionaryViewId = SpawnManager.Instance.pvViewId;
        if (dictionaryViewId.TryGetValue(viewId, out AvatarSetNumber avatar))
        {
            CustomAvatarController customAvatarController = avatar.GetComponent<CustomAvatarController>();
            customAvatarController.Die();
        }
    }

    private void DieRPC(int viewId)
    {
        if (PhotonNetwork.IsMasterClient)
        {
            photonView.RPC("LocalDie", RpcTarget.All, viewId);
        }
    }

    // RaycastЗЮ AttackРЬКЅЦЎ НЧЧр ИоМ­Ех
    public void AttackEnemy()
    {
        if (Physics.BoxCast(transform.position, boxSize / 2, transform.forward * 0.5f, out hit, Quaternion.identity, castDistance))
        {
            if (hit.collider.gameObject.layer == LayerMask.NameToLayer("Player"))
            {
                var pv = hit.collider.gameObject.GetComponent<PhotonView>();
                var id = pv.ViewID;
                if (SceneManager.GetActiveScene().name == "Map")
                {
                    CustomAvatarController customAvatarController = hit.collider.gameObject.GetComponent<CustomAvatarController>();

                    if (customAvatarController._isDead == true)
                    {
                        return;
                    }
                    else
                    {
                        DieRPC(id);
                        Debug.Log("Player Attack");
                    }
                }
            }
            else if (hit.collider.gameObject.layer == LayerMask.NameToLayer("Ai"))
            {
                var pv = hit.collider.gameObject.GetComponent<PhotonView>();
                var id = pv.ViewID;

                AIWalker aiwalker = hit.collider.gameObject.GetComponent<AIWalker>();

                if (aiwalker == null) { return; }

                if (SceneManager.GetActiveScene().name == "Map")
                {
                    Debug.Log("Ai Attack");
                    aiwalker.DieRPC(id);
                }
            }
        }
    }

}


