using System.Collections;
using System.Collections.Generic;
using Photon.Pun;
using UnityEngine;
using UnityEngine.UI;

public class PlayerAvatar : MonoBehaviourPun
{
    // ДаГзРгРЛ ЧЅНУЧЯДТ UI ХиНКЦЎ
    [SerializeField] private Text txtNickname;

    // УЄЦУ ГЛПыРЛ ЧЅНУЧЯДТ UI ХиНКЦЎ
    [SerializeField] private Text txtChat;

    // УЄЦУ ИЛЧГМБ ПРКъСЇЦЎ
    [SerializeField] private GameObject chatBubble;


    // ЧУЗЙРЬОюРЧ ПђСїРгРЛ СІОюЧЯДТ AvatarController ФФЦїГЭЦЎ
    private CustomAvatarController _controller;

    // ЧУЗЙРЬОюРЧ ДаГзРг
    public string _nickname;

    // ЧУЗЙРЬОюРЧ Photon ActorNumber (ГзЦЎПіХЉ ЛѓРЧ АэРЏ ЙјШЃ)
    public int _actorNumber;

    private Rigidbody _rb;


    RaycastHit hit;

    [SerializeField] private float MaxDistance = 15f;

    private void Awake()
    {
        // AvatarController ФФЦїГЭЦЎИІ АЁСЎПШ
        _controller = GetComponent<CustomAvatarController>();

        // УЄЦУ ИЛЧГМБРЛ КёШАМКШ­ЧЯПЉ УЪБт ЛѓХТИІ МћБш
        chatBubble.SetActive(false);

        _rb = GetComponent<Rigidbody>();
    }

    private void Update()
    {
        _rb.velocity = Vector3.zero;
    }


    // [PunRPC] ГзЦЎПіХЉИІ ХыЧи ШЃУтЕЧДТ ИоМ­Ех
    // ЧУЗЙРЬОюРЧ ДаГзРгАњ ActorNumberИІ МГСЄ
    [PunRPC]
    public void SetNickname(string nickname , int actorNumber)
    {
        _nickname = nickname;
        _actorNumber = actorNumber;

        // ДаГзРг UI ХиНКЦЎПЁ ЧЅНУ
        if (photonView.IsMine)
        {
            txtNickname.text = nickname;
        }
        else
        {
            txtNickname.text = ""; // ДйИЅ ЛчЖїПЁАдДТ ДаГзРг МћБтБт
        }
    }

    // ЧУЗЙРЬОюРЧ ПђСїРг АЁДЩ ПЉКЮИІ МГСЄ
    public void SetMovable(bool value)
    {
        _controller.canMove = value;
    }

    // ЦЏСЄ ActorNumberПЭ ЧіРч ОЦЙйХИРЧ ActorNumberИІ КёБГ
    // ЕПРЯЧб ОЦЙйХИРЮСі ШЎРЮЧЯДТ ИоМ­Ех
    public bool IsTargetAvatar(int actorNumber) => _actorNumber == actorNumber;

    // УЄЦУРЛ ЧЅНУЧЯДТ ИоМ­Ех
    // РЬЙЬ УЄЦУ ФкЗчЦОРЬ НЧЧр СпРЬЖѓИщ СпСіЧЯАэ Лѕ УЄЦУРЛ ЧЅНУ
    public void ShowChat(string chat)
    {
        if (_chatCoroutine != null)
            StopCoroutine(_chatCoroutine); // БтСИ ФкЗчЦО СпСі

        _chatCoroutine = ChatCoroutine(chat); // ЛѕЗЮПю ФкЗчЦО Л§МК
        StartCoroutine(_chatCoroutine); // ФкЗчЦО НЧЧр
    }

    // УЄЦУРЛ РЯСЄ НУАЃ ЕПОШ ЧЅНУЧЯАэ МћБтДТ ФкЗчЦО
    private IEnumerator _chatCoroutine;
    private IEnumerator ChatCoroutine(string chat)
    {
        // УЄЦУ ИЛЧГМБРЛ ШАМКШ­
        chatBubble.SetActive(true);

        // УЄЦУ ГЛПыРЛ ХиНКЦЎПЁ ЧЅНУ
        txtChat.text = chat;

        // 3УЪ ЕПОШ УЄЦУРЛ ЧЅНУw
        yield return new WaitForSeconds(3f);

        // УЄЦУ ГЛПыРЛ СіПьАэ ИЛЧГМБРЛ МћБш
        txtChat.text = null;
        chatBubble.SetActive(false);
    }
}
